#!/usr/bin/env python3
# =============================================================================
# img2c.py - Convert PNG/BMP/JPG to a C++ RGBA byte array for Nexy OS
#
# Usage:
#   python3 tools/img2c.py <image.png> <output.h> [max_width] [max_height]
#
# Example:
#   python3 tools/img2c.py Logo.png kernel/logo.h 120 30
#
# Requires: pip install pillow
# =============================================================================

import sys
import os
from PIL import Image

def convert(src: str, dst: str, max_w: int = None, max_h: int = None):
    img = Image.open(src).convert("RGBA")

    # Resize if dimensions specified
    if max_w and max_h:
        img.thumbnail((max_w, max_h), Image.LANCZOS)
    elif max_w:
        ratio = max_w / img.width
        img = img.resize((max_w, int(img.height * ratio)), Image.LANCZOS)
    elif max_h:
        ratio = max_h / img.height
        img = img.resize((int(img.width * ratio), max_h), Image.LANCZOS)

    w, h = img.size
    pixels = list(img.getdata()) if not hasattr(img, 'get_flattened_data') else list(img.get_flattened_data())  # RGBA tuples

    var_name = os.path.splitext(os.path.basename(src))[0].upper().replace("-", "_").replace(" ", "_")

    lines = []
    lines.append("#pragma once")
    lines.append("// Auto-generated by tools/img2c.py — DO NOT EDIT")
    lines.append(f"// Source: {os.path.basename(src)}  ({w}x{h} pixels, RGBA)")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"static const int {var_name}_W = {w};")
    lines.append(f"static const int {var_name}_H = {h};")
    lines.append("")
    lines.append(f"#define {var_name}_DATA_AVAILABLE")
    lines.append(f"static const uint8_t {var_name}_DATA[{h} * {w} * 4] = {{")

    row_strings = []
    for row in range(h):
        cols = []
        for col in range(w):
            r, g, b, a = pixels[row * w + col]
            cols.append(f"0x{r:02X},0x{g:02X},0x{b:02X},0x{a:02X}")
        row_strings.append("    " + ",".join(cols))

    lines.append(",\n".join(row_strings))
    lines.append("};")
    lines.append("")

    with open(dst, "w") as f:
        f.write("\n".join(lines))

    print(f"[img2c] {src} ({w}x{h}) → {dst}  ({w*h*4} bytes)")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: img2c.py <image> <output.h> [max_width] [max_height]")
        sys.exit(1)

    src_file = sys.argv[1]
    dst_file = sys.argv[2]
    mw = int(sys.argv[3]) if len(sys.argv) > 3 else None
    mh = int(sys.argv[4]) if len(sys.argv) > 4 else None

    convert(src_file, dst_file, mw, mh)
